project:
  type: website

website:
  title: "Yizhi Liang"
  back-to-top-navigation: true
  page-footer: "© 2024 Yizhi Liang"
  reader-mode: true
  
  navbar:
    background: primary
    foreground: light
    pinned: true
    search: true
    left:
      - text: "Blog"
        file: index.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css



